name: SaveRotatingShop
version: 1.0.0
main: fun.lewisdev.saverotatingshop.SaveDynamicShop
api-version: 1.18.2
authors: [ValdemarF]

depend: [ProtocolLib, Vault]

permissions:
  saverotatingshop.admin:
    default: op
